apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: kiii-crud
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: postgres
  DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
  FRONTEND_URL: http://frontend:80
